// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MySql.Data.EntityFrameworkCore.Storage.Internal;
using SICORA.Models;
using System;

namespace SICORA.Migrations
{
    [DbContext(typeof(MvcContext))]
    [Migration("20181110215447_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("SICORA.Models.Juegos", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Desc_juego");

                    b.Property<string>("Img_juego");

                    b.Property<string>("Nom_juego");

                    b.Property<string>("pre_juego");

                    b.Property<string>("trailer_juego");

                    b.HasKey("ID");

                    b.ToTable("Juegos");
                });

            modelBuilder.Entity("SICORA.Models.Perifericos", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Desc_perifericos");

                    b.Property<string>("Img_perifericos");

                    b.Property<string>("Nom_perifericos");

                    b.Property<string>("pre_perifericos");

                    b.HasKey("ID");

                    b.ToTable("Perifericos");
                });

            modelBuilder.Entity("SICORA.Models.Programas", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Desc_programa");

                    b.Property<string>("Img_programa");

                    b.Property<string>("Nom_programa");

                    b.Property<string>("pre_programa");

                    b.HasKey("ID");

                    b.ToTable("Programas");
                });

            modelBuilder.Entity("SICORA.Models.Prueba_bd", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Desc_juego");

                    b.Property<string>("Imagen_juego");

                    b.Property<string>("Nom_juego");

                    b.Property<string>("Pre_juego");

                    b.Property<string>("Trailer_juego");

                    b.HasKey("ID");

                    b.ToTable("Prueba_bd");
                });
#pragma warning restore 612, 618
        }
    }
}
